version: '3'
services:
  order-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./order-service/
      args:
        jarDir: ${JAR_DIR:-target}
        serviceImageVersion: 0.1.0-SNAPSHOT
        baseImageVersion: BUILD-15
    image: saga-research/order-service:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - "8081:8080"
      - "5005:5005"
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - cdc-service
    restart: always
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CDC_SERVICE_URL: http://cdc-service:8080
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  basket-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./basket-service/
      args:
        jarDir: ${JAR_DIR:-target}
        serviceImageVersion: 0.1.0-SNAPSHOT
        baseImageVersion: BUILD-15
    image: saga-research/basket-service:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - "8082:8080"
      - "5006:5006"
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - cdc-service
    restart: always
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CDC_SERVICE_URL: http://cdc-service:8080
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  product-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./product-service/
      args:
        jarDir: ${JAR_DIR:-target}
        serviceImageVersion: 0.1.0-SNAPSHOT
        baseImageVersion: BUILD-15
    image: saga-research/product-service:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - "8083:8080"
      - "5007:5007"
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - cdc-service
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CDC_SERVICE_URL: http://cdc-service:8080
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  zookeeper:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    image: "eventuateio/eventuate-zookeeper:0.18.0.RELEASE"
    ports:
      - 2181:2181
    environment:
      EVENTUATE_COMMON_VERSION: 0.18.0.RELEASE
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: -Xmx64m

  kafka:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    image: "eventuateio/eventuate-kafka:0.18.0.RELEASE"
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx192m

  mysql:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    image: eventuateio/eventuate-mysql8:0.18.0.RELEASE
    ports:
      - 3306:3306
    environment:
      - EVENTUATE_COMMON_VERSION=0.18.0.RELEASE
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  mongodb:
    image: mongo:5.0.6
    ports:
      - "27017:27017"

  cdc-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    image: eventuateio/eventuate-cdc-service:0.16.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      EVENTUATE_CDC_KAFKA_ENABLE_BATCH_PROCESSING: ${EVENTUATE_CDC_KAFKA_ENABLE_BATCH_PROCESSING:-false}
      EVENTUATE_OUTBOX_ID: 1
      JAVA_OPTS: -Xmx64m

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    environment:
      JAVA_OPTS: -Xmx64m
